### ISSUE TITLE
subprocess.CalledProcessError: Command [snap/bin/gpt]

### ISSUE THREAD

**Issue by acardaras-sanborn** [kleok/FLOODPY#61] opened 2023-03-10 17:12 UTC
I occasionally encounter an error related to the gpt subprocess on different AOI's. I've attached an image of the error message and provided an example .cfg file modification that causes this error on my machine. 

```
# B1. The datetime of flood event (Format is YYYYMMDDTHHMMSS)
Flood_datetime = 20170910T043000

# B2. Days before flood event for baseline stack construction
before_flood_days = 60

# B3. Days after flood event
after_flood_days = 10

# C2. AOI BBOX (WGS84)
LONMIN=-81.46
LATMIN=24.61
LONMAX=-81.29
LATMAX=24.74
```

![image](https://user-images.githubusercontent.com/112427170/224377790-9020a32b-7ee9-450d-9672-2fe877c87d8c.png)

**Comment by kleok** [comment] 2023-04-14 17:37
Hello @acardaras-sanborn,
I was able to reproduce your error on the given configuration.
![image](https://user-images.githubusercontent.com/7121726/232110892-9aaac22e-a44b-4e79-bfd6-a82bdb70d688.png)
As you can see in this printcreeen the backscatter of the flood image (right image) does not look like that the backscatter in the pre-flood images. I believe that the particular error you encounter is because the coregistration fails. I committed some changes and now if you have coregistration errors with some image, this image is dropped and the processing continues.

I managed to run FloodPy successfuly in your AOI, by modifing ```after_flood_days=120```. I hope this helps :smile: 
Let me know if anything further is needed

**Closed** 2023-05-21 17:59 UTC
